# This is for running the launcher app, not for the app itself
version: "3"

services:

  launcher-go:
    image: golang:alpine
    restart: unless-stopped
    container_name: launcher-go
    expose:
      - 8080
    volumes:
      - .:/app:ro
    environment:
      - LETSENCRYPT_EMAIL=${LE_EMAIL}
      - VIRTUAL_HOST=${LE_HOSTNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${LE_HOSTNAME}
    working_dir: /app
    entrypoint: ["go", "run", "main.go"]

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion:latest
    restart: unless-stopped
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro